version: '3.7'
services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - app-network

#  postgres:
#    image: postgres:14.1-alpine
#    container_name: postgres-container
#    restart: always
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    networks:
#      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres-container
    environment:
      - POSTGRES_MULTIPLE_DATABASES=dev,test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./build/postgres/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    networks:
      - app-network

  php:
    container_name: php-container
    build:
      context: ./build
      dockerfile: ./php/Dockerfile
    ports:
      - "9000:9000"
    environment:
      APP_ENV: dev
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge