get_posts:
    path: /posts
    methods: GET
    controller: App\UI\Action\GetPostsAction

add_posts:
    path: /posts
    methods: POST
    controller: App\UI\Action\AddPostsAction

delete_posts:
    path: /posts
    methods: DELETE
    controller: App\UI\Action\DeletePostsAction

update_posts:
    path: /posts
    methods: PUT
    controller: App\UI\Action\UpdatePostsAction

registration:
    path: /registration
    methods: POST
    controller: App\UI\Action\RegistrationAction

api_login_check:
    path: /api/login_check