<?php

namespace App\Application\Enum;

enum Error: string
{
    case ADD_POST_ACTION_ERROR = 'ADD_POST_ACTION_ERROR';
    case UPDATE_POST_ACTION_ERROR = 'UPDATE_POST_ACTION_ERROR';
    case DELETE_POST_ACTION_ERROR = 'DELETE_POST_ACTION_ERROR';
    case GET_POST_ACTION_ERROR = 'GET_POST_ACTION_ERROR';
    case REGISTRATION_ERROR = 'REGISTRATION_ERROR';
}
